# Generated by Django 3.0.3 on 2020-09-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='password',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
