# Generated by Django 3.0.3 on 2020-09-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_profiles_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
