# Generated by Django 3.0.3 on 2020-09-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_auto_20200919_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=264, unique=True)),
                ('password', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
